site:
  title: PoC Revolution Pi Dokumentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://shartleib.github.io/revpidoc
  start_page: revpidoc::index.adoc
content:
  sources:
    - url: ./
      branches:
        - main
      edit_url: "https://github.com/shartleib/revpidoc/docs/edit/main/{path}"
      start_path: docs
antora:
  extensions:
    - require: "@antora/lunr-extension" # https://gitlab.com/antora/antora-lunr-extension/
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
runtime:
  log:
    level: info
    failure_level: warn
    format: pretty
  fetch: true
  cache_dir: ./.cache/antora