site:
  title: PoC Revolution Pi Dokumentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://shartleib.github.io/revpidoc
  start_page: docs::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true