= Revolution Pi

== About Revolution Pi
Revolution Pi is an open, modular and inexpensive industrial PC based on the well-known Raspberry Pi. Housed in a slim DIN-rail housing, the three available base modules can be seamlessly expanded by a variety of suitable I/O modules and fieldbus gateways. The 24V powered modules are connected via an overhead connector in seconds and can be easily configured via a graphical configuration tool.

To achieve a real industrial suitability according to EN 61131-2 or IEC 61131-2, the rather unknown Raspberry Pi Compute Module was used as a basis. The module, which looks like a notebook RAM bar, is limited to the essentials and does not have any external interfaces. With the Raspberry Pi Compute Module the foundation has been laid for equipping the Raspberry Pi with a robust and industry-compatible periphery developed by us, which meets all important industrial standards. On the software side, the Revolution Pi has a specially adapted Raspberry Pi OS (formerly known as Raspbian) operating system, which is equipped with a real-time patch. The use of Raspberry Pi OS ensures that most of the applications developed for the Raspberry Pi can also be used on the Revolution Pi.

== About this documentation

TEXT 游때九껊잺
TEXT 游때九껊잺
TEXT 游때九껊잺
TEXT 游때九껊잺

=== documentation repository struktur

[listing#ex-modules]
----
游 repository
    游늭 export
    游늭 modules
        游늭 ROOT
            游늬 images
            游늭 pages
                游늭 examples
                游늭 faq
                游늭 legacy_hardware
                游늭 revpi_hardware
                游늭 revpi_software
                游늯 index.adoc
            游늭 partials
            游늯 nav.adoc
    游늯 antora.yml
----
