= RevPi installation

Revolution Pi is able to run a wide range of software in industrial environments, including a number of different operating systems – the core software that makes a computer run. The most popular of these, and the official operating system of the Raspberry Pi Foundation, is Raspberry Pi OS. Based on Debian Linux, we're tailor-made it for the Revolution Pi and it comes with a range of extras pre-installed and ready to go.

If you’ve only ever used Microsoft Windows or Apple macOS, don’t worry: Raspberry Pi OS is based on the same windows, icons, menus, and pointer (WIMP) principles, and should quickly feel familiar. The following chapter will get you started and introduce you to some of the bundled software.

== Connect remote to your RevPi via SSH

SSH (Secure Shell) is a protocol used for securely connecting to and executing commands on remote systems, in case your RevPi. It solves the problem of potential data interception in insecure networks by encrypting all transmitted information.

NOTE: To connect to your RevPi securely you only need to know its IP none or the names SN*.local

=== For Windows

. Download and install PuTTY, a free SSH client for Windows. You can download it from this URL: https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

. Once installed, open PuTTY.

. In the 'Host Name (or IP address)' field, enter the IP address of your RevPi.

. Ensure that the Port is set to 22 (this is the default port for SSH).

. Click 'Open'.

. If this is your first time connecting to the RevPi from this computer, you'll receive a warning. Click 'Yes' to continue.

. You will be prompted to enter your username and password for the RevPi. The default username is `pi` and the password is on the right side of your device.

=== For Mac OS

. Open Terminal (You can find Terminal in Applications -> Utilities, or by searching for it in Spotlight).

. Type the following command, replacing 'your_pi_ip' with your RevPi's IP address: `ssh pi@your_pi_ip`

. The first time you connect, you'll see a message saying the authenticity of the host can't be established. Type 'yes' to continue.

. You'll then be prompted to enter your RevPi's password. As with Windows, the default username is `pi` and the password is on the right side of your device.

=== For Linux

The process for Debian Linux is very similar to the process for Mac.

. Open a terminal.

. Use the SSH command to connect to your RevPi, replacing 'your_pi_ip' with your RevPi's IP address: `ssh pi@your_pi_ip`

. Like with the Mac, you'll see a message about the authenticity of the host the first time you connect. Type 'yes' to continue.

. Enter your password when prompted. The default username is `pi` and the password is on the right side of your device.


== Connect remote to your RevPi via VNC

VNC, or Virtual Network Computing, is a graphical desktop sharing system that uses the Remote Frame Buffer protocol to remotely control another computer. It transmits the keyboard and mouse events from one computer to another, relaying the graphical screen updates back in the other direction, over a network.

The problem VNC solves is the need for remote access to a computer system's graphical desktop environment. This can be useful in various scenarios such as technical support, remote work, or managing servers that are physically located in different places. It allows the user to interact with the remote machine as if they were sitting directly in front of it, even if the two machines are geographically far apart.

NOTE: To connect to your RevPi using RealVNC, you must have the VNC Server running on your RevPi. You can enable this by going to the RevPi configuration settings (`sudo raspi-config`) > `Interface Options` > `VNC` > `Yes`.

=== For Windows:

. Download and install the VNC Viewer from the RealVNC website: https://www.realvnc.com/en/connect/download/combined/

. Open VNC Viewer and click on the `File` menu and then `New Connection`.

. In the VNC Server field, enter the IP address of your RevPi.

. Click OK.

. Now, in the main viewer window, double-click on the new connection you just created.

. You'll be asked for a username and password. If you haven't changed these on your RevPi, they'll be "pi" and "raspberry", respectively.

. You're now connected to your RevPi via RealVNC from your Windows PC.

=== For Mac:

. Download and install the VNC Viewer from the RealVNC website: https://www.realvnc.com/en/connect/download/combined/

. Open VNC Viewer from your Applications folder.

. Click on `File` > `New Connection`.

. In the VNC Server field, enter the IP address of your RevPi.
. Click OK.

. In the main viewer window, double-click on the new connection.

. You'll be asked for a username and password. If you haven't changed these on your RevPi, they'll be "pi" and "raspberry", respectively.

. You're now connected to your RevPi via RealVNC from your Mac.

=== For Debian Linux:

. Open your terminal.

. Install VNC Viewer by typing the following command and pressing Enter: `sudo apt-get install realvnc-vnc-viewer`

. After the installation, run VNC Viewer by typing `vncviewer` and pressing Enter.

. In the VNC Server field, enter the IP address of your RevPi and press Enter.

. You'll be asked for a username and password. If you haven't changed these on your RevPi, they'll be "pi" and "raspberry", respectively.

. You're now connected to your RevPi via RealVNC from your Debian Linux machine.


== Ethernet Ports

Übersicht der Geräte und ports 2 x RJ45 GBit Ethernet sockets

IMPORTANT: In Linux eth0 = Port A, eth1 = Port B on your device.

=== Check the IPv4 configuration

Open the Terminal application on your Revolution Pi or connect via SSH to your RevPi and identify the interface on which we will configure static IP address. Run below ip command:

[source,bash]
----
$ ip add show
----

The result looks like this:

[source,bash]
----
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether c8:3e:a7:01:6b:f7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.88.246/24 brd 192.168.88.255 scope global dynamic noprefixroute eth0
       valid_lft 1730sec preferred_lft 1730sec
    inet6 fe80::ca3e:a7ff:fe01:6bf7/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether c8:3e:a7:01:6b:f8 brd ff:ff:ff:ff:ff:ff
4: pileft: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether f6:7b:65:df:2f:12 brd ff:ff:ff:ff:ff:ff
----

=== Check the network connection for function

*nmcli* is a command-line tool for controlling NetworkManager and reporting network status. It can be utilized as a replacement for nm-applet or other graphical clients. nmcli is used to create, display, edit, delete, activate, and deactivate network connections, as well as control and display network device status.

Run below ip command:

[source,bash]
----
$ nmcli connection
----

The result looks like this:

[source,bash]
----
NAME                        UUID                                  TYPE      DEVICE
DHCP eth0                   d1ae9f0b-c8a7-42aa-a238-8f1e9668f5ef  ethernet  eth0
DHCP eth1                   4e764ae2-0a96-11ee-b8b2-97bdf6db4268  ethernet  --
Link-local eth0 (fallback)  a9883125-de1f-4d75-a049-124ee2adcff4  ethernet  --
Link-local eth1 (fallback)  02418238-fb3a-11ed-8321-c3d5d52b169a  ethernet  --
----

=== Set the IPv4 configuration to static

By default, the Ethernet ports of the Revolution Pi are set to DHCP and get an IP from the network.

==== Run the *nmcli* command to get the connection NAME

[source,bash]
----
$ nmcli connection
----

The result looks like this:

[source,bash]
----
NAME                        UUID                                  TYPE      DEVICE
DHCP eth0                   d1ae9f0b-c8a7-42aa-a238-8f1e9668f5ef  ethernet  eth0
DHCP eth1                   4e764ae2-0a96-11ee-b8b2-97bdf6db4268  ethernet  --
Link-local eth0 (fallback)  a9883125-de1f-4d75-a049-124ee2adcff4  ethernet  --
Link-local eth1 (fallback)  02418238-fb3a-11ed-8321-c3d5d52b169a  ethernet  --
----

Once we get the connection NAME *'DHCP eth0'*

==== Run below nmcli command to assign static ipv4 address

Syntax:: $ nmcli con mod  ‘connection-name’ ipv4.address  <IP-Address>

[source,bash]
----
$ nmcli con mod 'DHCP eth0' ipv4.address 192.168.1.151/24
----

==== Set the gateway IP by running the command below

[source,bash]
----
$ nmcli con mod 'DHCP eth0' ipv4.gateway 192.168.1.1
----

==== Change Configuration from DHCP to Manual
This way the IP is set static and persistent on the eth0

[source,bash]
----
$ nmcli con mod 'DHCP eth0' ipv4.method manual
----

==== Set the DNS server IP

DNS server translates domain names to IP addresses for the internet. Add a DNS Server IP by running below command:

[source,bash]
----
$ nmcli con mod 'DHCP eth0' ipv4.dns '8.8.8.8'
----

==== Make the IPv4 changes operative

WARNING: If you execute this command and are connected to the device remotely via SSH, the connection will be terminated and can no longer be activated. You must then restart the device or use the second Ethernet interface on which DHCP is still active.

Disable and enable the connection so that above changes come into the effect.

[source,bash]
----
$ nmcli connection down d1ae9f0b-c8a7-42aa-a238-8f1e9668f5ef
----

[source,bash]
----
$ nmcli connection up d1ae9f0b-c8a7-42aa-a238-8f1e9668f5ef
----

==== Result

Now Run IP Command to check IP address,

[source,bash]
----
$ ip add show eth0
----

The result looks like this:

[source,bash]
----
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether c8:3e:a7:01:6b:f7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.88.10/24 brd 192.168.88.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ca3e:a7ff:fe01:6bf7/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
----

== Raspberry Pi Compute Module
|===
|Feature |CM1 |CM3/3+ |CM4S |CM4

|Processor
|BCM2835
|BCM2837
|BCM2711
|BCM2711

|Memory RAM
|512MB
|1GB
|1GB
|1GB/2GB/4GB/8GB

|Memory eMMC
|
|0/8/16/32GB
|0/8/16/32GB
|0/8/16/32GB

|Ethernet
|None
|None
|None
|1xGBit ethernet

|USB
|1 x USB2.0
|1 x USB2.0
|1 x USB2.0
|1 x USB2.0

|HDMI
|1 x 1080p60
|1 x 1080p60
|1 x 4k
|1 x 4k

|WiFi
|None
|None
|None
|2.4GHz/5.0GHz 802.11b/g/n/ac (opt)

|Bluetooth
|None
|None
|None
|5.0, BLE (opt)

|PCIe
|None
|None
|None
|PCIe 1-lane Host, Gen 2 ( 5Gbps )

|(usable) GPIOs
|48
|48
|48
|28

|Form factor
|SODIMM
|SODIMM
|SODIMM
|DF40C-100DS-0.4v, DF40HC(3.0)-100DS-0.4v
|===
