= RevPi installation

[TIP]
====
Use our forum to connect and discuss with the Revolution Pi community. -> link:https://revolutionpi.com/forum/[Revolution Pi Forum]
====

== Ethernet Ports

IMPORTANT: In Linux eth0 = Port A, eth1 = Port B on your device.

=== Check the IPv4 configuration

Open the Terminal application on your Revolution Pi or connect via SSH to your RevPi and identify the interface on which we will configure static IP address. Run below ip command:

[source,bash]
----
$ ip add show
----

The result looks like this:

[source,bash]
----
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether c8:3e:a7:01:6b:f7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.88.246/24 brd 192.168.88.255 scope global dynamic noprefixroute eth0
       valid_lft 1730sec preferred_lft 1730sec
    inet6 fe80::ca3e:a7ff:fe01:6bf7/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether c8:3e:a7:01:6b:f8 brd ff:ff:ff:ff:ff:ff
4: pileft: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether f6:7b:65:df:2f:12 brd ff:ff:ff:ff:ff:ff
----

=== Check the network connection for function

*nmcli* is a command-line tool for controlling NetworkManager and reporting network status. It can be utilized as a replacement for nm-applet or other graphical clients. nmcli is used to create, display, edit, delete, activate, and deactivate network connections, as well as control and display network device status.

Run below ip command:

[source,bash]
----
$ nmcli connection
----

The result looks like this:

[source,bash]
----
NAME                        UUID                                  TYPE      DEVICE
DHCP eth0                   d1ae9f0b-c8a7-42aa-a238-8f1e9668f5ef  ethernet  eth0
DHCP eth1                   4e764ae2-0a96-11ee-b8b2-97bdf6db4268  ethernet  --
Link-local eth0 (fallback)  a9883125-de1f-4d75-a049-124ee2adcff4  ethernet  --
Link-local eth1 (fallback)  02418238-fb3a-11ed-8321-c3d5d52b169a  ethernet  --
----

=== Set the IPv4 configuration to static

By default, the Ethernet ports of the Revolution Pi are set to DHCP and get an IP from the network.

==== Run the *nmcli* command to get the connection NAME

[source,bash]
----
$ nmcli connection
----

The result looks like this:

[source,bash]
----
NAME                        UUID                                  TYPE      DEVICE
DHCP eth0                   d1ae9f0b-c8a7-42aa-a238-8f1e9668f5ef  ethernet  eth0
DHCP eth1                   4e764ae2-0a96-11ee-b8b2-97bdf6db4268  ethernet  --
Link-local eth0 (fallback)  a9883125-de1f-4d75-a049-124ee2adcff4  ethernet  --
Link-local eth1 (fallback)  02418238-fb3a-11ed-8321-c3d5d52b169a  ethernet  --
----

Once we get the connection NAME *'DHCP eth0'*

==== Run below nmcli command to assign static ipv4 address

Syntax:: $ nmcli con mod  ‘connection-name’ ipv4.address  <IP-Address>

[source,bash]
----
$ nmcli con mod 'DHCP eth0' ipv4.address 192.168.1.151/24
----

==== Set the gateway IP by running the command below

[source,bash]
----
$ nmcli con mod 'DHCP eth0' ipv4.gateway 192.168.1.1
----

==== Change Configuration from DHCP to Manual
This way the IP is set static and persistent on the eth0

[source,bash]
----
$ nmcli con mod 'DHCP eth0' ipv4.method manual
----

==== Set the DNS server IP

DNS server translates domain names to IP addresses for the internet. Add a DNS Server IP by running below command:

[source,bash]
----
$ nmcli con mod 'DHCP eth0' ipv4.dns '8.8.8.8'
----

==== Make the IPv4 changes operative

WARNING: If you execute this command and are connected to the device remotely via SSH, the connection will be terminated and can no longer be activated. You must then restart the device or use the second Ethernet interface on which DHCP is still active.

Disable and enable the connection so that above changes come into the effect.

[source,bash]
----
$ nmcli connection down d1ae9f0b-c8a7-42aa-a238-8f1e9668f5ef
----

[source,bash]
----
$ nmcli connection up d1ae9f0b-c8a7-42aa-a238-8f1e9668f5ef
----

==== Result

Now Run IP Command to check IP address,

[source,bash]
----
$ ip add show eth0
----

The result looks like this:

[source,bash]
----
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether c8:3e:a7:01:6b:f7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.88.10/24 brd 192.168.88.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ca3e:a7ff:fe01:6bf7/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
----

🥳🥳🥳

== technical Data

=== Raspberry Pi Compute Module
|===
|Feature |CM1 |CM3/3+ |CM4S |CM4

|Processor
|BCM2835
|BCM2837
|BCM2711
|BCM2711

|Memory RAM
|512MB
|1GB
|1GB
|1GB/2GB/4GB/8GB

|Memory eMMC
|
|0/8/16/32GB
|0/8/16/32GB
|0/8/16/32GB

|Ethernet
|None
|None
|None
|1xGBit ethernet

|USB
|1 x USB2.0
|1 x USB2.0
|1 x USB2.0
|1 x USB2.0

|HDMI
|1 x 1080p60
|1 x 1080p60
|1 x 4k
|1 x 4k

|WiFi
|None
|None
|None
|2.4GHz/5.0GHz 802.11b/g/n/ac (opt)

|Bluetooth
|None
|None
|None
|5.0, BLE (opt)

|PCIe
|None
|None
|None
|PCIe 1-lane Host, Gen 2 ( 5Gbps )

|(usable) GPIOs
|48
|48
|48
|28

|Form factor
|SODIMM
|SODIMM
|SODIMM
|DF40C-100DS-0.4v, DF40HC(3.0)-100DS-0.4v
|===
