= Docker Container and Docker Compose

== What is a Docker Container?
A Docker container is like a virtual box that encloses an application and everything it needs to run. Inside this box are the application software, libraries, and settings needed to run the application. Docker containers are isolated and can run on different computers and servers, regardless of the environment they are launched on. This makes applications in containers portable and easy to manage. Docker containers are a way to run applications in clean and separate environments, which prevents problems when different applications run on the same computer.

== What is Docker Compose?

Docker Compose is a tool that allows you to define, configure, and manage multiple Docker containers together as part of an application. It uses a YAML file (usually called docker-compose.yml) to define the configuration of the containers and their relationships to each other.
Docker Compose lets you group multiple services and containers into one application, which is especially useful if your application consists of multiple components, such as a web application, a database, and a cache.
Docker Compose provides commands to start, stop, and manage the entire application or individual services in the application. This makes it easier to deploy and scale complex applications.

== Why to use Docker on your RevPi?

Using Docker and Docker Compose on your RevPi can make sense for several reasons:

Isolation of applications::: Docker enables containerization of applications. This means that each application runs in its own container, isolated from other applications and the RevPi operating system. This makes deploying and managing applications easier by avoiding conflicts between applications.

Portability::: Docker containers are portable and can easily run on different platforms, including your RevPi. This makes it easier to develop and test applications on a powerful development machine and then deploy them to your RevPi.

Resource management::: Docker allows you to control and limit the resources used by containers. This is especially useful on your RevPi because its resources are limited. You can specify how much CPU, RAM, and storage each container is allowed to use to ensure that your RevPi is used efficiently.

Easy scalability::: With Docker Compose, you can easily launch and manage multiple containers at once, making it easy to scale your applications. For example, if you are running a web application with a database, you can run both in separate containers and easily launch them together using Docker Compose.

Updates and rollbacks::: Docker allows you to easily update images and containers and roll back to previous versions if needed. This is useful when you want to test application updates and quickly roll back to the previous version if you encounter problems.

Community and ecosystem::: Docker has a large user and developer community, as well as a rich ecosystem of pre-built containers and tools. This makes it easier to integrate applications and solve problems.

Recoverability::: Using Docker containers makes it easier to recover your RevPi applications in case the Raspberry Pi fails or needs to be replaced. All you have to do is back up your container configuration and data, and then you can quickly restore to a new Raspberry Pi.

NOTE: Overall, Docker provides an efficient way to run applications on your RevPi by improving isolation, portability, resource management, scalability, and simplifying application management. This is especially useful in environments where you want to host multiple services or applications on your RevPi.

== 32-bit or 64-bit OS

Choosing between Revolution Pi OS 32-bit and 64-bit can have implications for the use of Docker. Here are some important considerations:

Revolution Pi OS 32-Bit

Compatibility::: Revolution Pi OS 32-bit is more compatible with older hardware and software. If you're using applications that only offer 32-bit support, this might be the better choice.

Limited Memory Access::: 32-bit operating systems are limited to a finite amount of memory, typically less than 4 GB of RAM. This can constrain the performance and scalability of Docker applications if you require more RAM.

Revolution Pi OS 64-Bit

Improved Performance::: Raspberry Pi OS 64-bit can benefit from 64-bit-capable hardware and potentially offers better performance and memory management, especially if you have over 4 GB of RAM.

64-Bit Docker::: If you intend to run Docker containers with 64-bit applications, a 64-bit operating system is required. Some applications, especially in the x86-64 world, are only available for 64-bit systems.

Up-to-Date Software::: Some software packages and libraries are better optimized for 64-bit systems, and you gain access to newer 64-bit applications and developments.

NOTE: Keep in mind that Docker generally works better on 64-bit systems by default and is supported by many official Docker images. If you plan to run many Docker containers or containerized applications with 64-bit requirements, using Raspberry Pi OS 64-bit is likely the better choice. Ensure that your hardware is also 64-bit-capable, as older Raspberry Pi models may not be supported.

You find the DOWNLOAD for the 64-bit Image of Revolution Pi OS here:

    RevPi Bullseye 64-bit (08/2023) (ID: 7320)
    Customized version of Raspberry Pi OS Bullseye 64-bit suitable for Revolution Pi.
    MD5 Hash: ad0c539f6d7a6d25a75db99587a48041
    https://revolutionpi.com/download/7320/?tmstv=1696406763

    RevPi Bullseye 64-bit Lite (08/2023) (ID: 7322)
    Customized version of Raspberry Pi OS Bullseye 64-bit Lite suitable for Revolution Pi.
    MD5 Hash: 8d246bfba5f47dd8e65f8a9dc5e89b61
    https://revolutionpi.com/download/7322/?tmstv=1696406763

== Install Docker on your RevPi

Installing Docker CE (Community Edition) on the Revolution Pi OS requires running just a few commands. The best way to install Docker is to fetch it from the official Docker repositories, so to ensure that you’re always running the latest version.

To install Docker CE on your RevPi, both 32-bit and 64-bit, run:

. Install some required packages first

    sudo apt update

    sudo apt install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg2 \
        software-properties-common

. Get the Docker signing key for packages

    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -

. Add the Docker official repos
echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
     $(lsb_release -cs) stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list

. Install Docker

    sudo apt update

    sudo apt install -y --no-install-recommends \
        docker-ce \
        cgroupfs-mount

. At this point, we just need to run two more commands to have the Docker service started and automatically launched at boot.

    sudo systemctl enable --now docker

. Now that we have Docker running, we can test it by running the “hello world” image:

    sudo docker run --rm hello-world

. If everything is working, the command above will output something similar to: